export { renderSlot } from './helpers/renderSlot'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'
export { h } from './h'
export { createRenderer, RendererOptions } from './renderer'
export { onBeforeMount, onMounted, onBeforeUpdate, onUpdated } from './apiLifecycle'
export { nextTick } from './scheduler'
export { watch, watchEffect } from './apiWatch'
